### ISSUE TITLE
improve use of "form-data" package

### ISSUE THREAD

**Issue by edgedemon** [onfido/onfido-node#14]
i can see that for the upload functions youre using "axios" together with "form-data" to generate the requests, however your implementation is intentionally ignoring the form-data module options parameters.

your implementation in formatting.ts uses this code, which always uses only key and value for the form fields:

`
export const toFormData = (object: SimpleObject): FormData => {
  return Object.entries(object).reduce((formData, [key, value]) => {
    if (value !== undefined && value !== null) {
      formData.append(snakeCase(key), value);
    }
    return formData;
  }, new FormData());
};
`

this is specially bothersome when uploading files since form-data, is compatible with any StreamReader, given you pass the correct values, like in this example from form-data package:

`
  var form = new FormData();
  form.append('file', stdout, {
    filename: 'unicycle.jpg', // ... or:
    filepath: 'photos/toys/unicycle.jpg',
    contentType: 'image/jpeg',
    knownLength: 19806
  });
`

the workaround i found is adding a fake path into the stream buffer, to trick form-data into thinking this is a fs.ReadStream

 `
   const base64Data = '...any base 64 data here...'
    const buffer = Buffer.from(base64Data, 'base64')
    const bufferStream = new stream.PassThrough()
    bufferStream.end(buffer)
    bufferStream.path = './file.jpg'
    const documentRequest = {
      applicantId: profileId,
      file: bufferStream,
      type: type
    }
    const docData = await onfido.document.upload(documentRequest)
`

processing objects into your toFormData function would be cleaner, perhpas something like this 

`
export const toFormData = (object: SimpleObject): FormData => {
  return Object.entries(object).reduce((formData, [key, value]) => {
    if (value !== undefined && value !== null) {
       if (!(value instanceof Object)) {
          formData.append(snakeCase(key), value);
       } else {
            formData.append(snakeCase(key), value.value, value.options);
       }
    }
    return formData;
  }, new FormData());
};
`

which would allow this code instead

 `
   const base64Data = '...any base 64 data here...'
    const buffer = Buffer.from(base64Data, 'base64')
    const bufferStream = new stream.PassThrough()
    bufferStream.end(buffer)
    const documentRequest = {
      applicantId: profileId,
      file: {  value: bufferStream,
               options: {
                     contentType: 'image/jpeg'
                 }
             }
      type: type
    }
    const docData = await onfido.document.upload(documentRequest)
`

**Comment by ciaran16** [comment]
Hi @edgedemon, apologies for taking a while to address this. I've merged in a change that should let you use buffers without needing to use a workaround:

```js
const buffer = Buffer.from(base64Data, 'base64');
const bufferStream = new PassThrough();
bufferStream.end(buffer);

const document = await onfido.document.upload({
  applicantId: 'applicant-123',
  file: {
    contents: bufferStream,
    filepath: 'path/to/file.jpg',
    contentType: 'image/jpeg'
  },
  type: type
});
```

I'll release this in the next few days in `v1.2.0`. Let me know if you have any feedback.

**Comment by ciaran16** [comment]
Closing this since it's now released.
