### ISSUE TITLE
Couldn't find the download link the PDF report for Check when using Onfido API v3

### ISSUE THREAD

**Issue by jun-nguyen-goldenowl** [onfido/onfido-node#23]
**Description**

I used to get the download link for PDF output file generated for a Check using Onfido API v2 using the package [onfido](https://www.npmjs.com/package/onfido). After moving to the new package [@onfido/api](https://www.npmjs.com/package/@onfido/api), which is using Onfido API V3, I can't get the download link anymore.

Please help me!

**Refs**
- Check object from Onfido API v2: https://documentation.onfido.com/v2/#check-object
- Check object from Onfido API v3: https://documentation.onfido.com/#check-object

**Screenshots**
`Check object` response from Onfido API v2
![image](https://user-images.githubusercontent.com/52815696/88874644-bd624100-d249-11ea-9bbf-49273249718d.png)

**Comment by jun-nguyen-goldenowl** [comment]
@markwilson  @nickpellant  @sardaukar  @seewah Anyone can help me?

**Comment by ciaran16** [comment]
Hi @jun-nguyen-goldenowl, unfortunately the `download_uri` is not available in API v3 so also isn't available in this library. Currently it is only available in API v2, so you'd need to continue to use either the old library or make a direct API call to API v2 if you need to still get the `download_uri`.

Could you email api@onfido.com if you have questions about the API? They will be able to provide you with better and quicker support.
