### ISSUE TITLE
Type declaration file not present on package dist root directory.

### ISSUE THREAD

**Issue by Santiago8888** [onfido/onfido-node#26]
Hi, is an awesome product you have developed. I just wanted to let you that when installing the package.

The index.d.ts file is located inside the src directory instead of the root dist directory next to the index.js file. This causes the types to be missed on Cloud9 when using Typescript. I am using @onfido/api@1.5.1

Thanks in advance! And I'm looking forward to work on your API.

**Comment by bradennapier** [comment]
Also running into this.

**Comment by ciaran16** [comment]
Thanks for spotting this, should be fixed in v1.5.2
