### ISSUE TITLE
Image upload with node library

### ISSUE THREAD

**Issue by mkapiczy** [onfido/onfido-node#31]
Hi,

I know it's not an issue but a question but I hope you'll forgive me and will be able to help.

So I am trying to send a file (DL front/back and face photo to onfido with node library). I am getting the image data from my API as base64 encoded data. For testing I am using this site https://www.base64-image.de/ to base64 encode the file and send it to my API.

In my api I transform the base64 data to a readable like so:
```
export const convertFile = (base64Encoded: string): Readable => {
    const buffer = Buffer.from(base64Encoded, 'base64');
    return new Readable({
        read() {
            this.push(buffer);
            this.push(null);
        }
    });
};
```

and then I am passing it to onfido library:

```
await onfido.document.upload({
        applicantId: applicantId,
        side: 'front'
        type: DocumentType.DRIVING_LICENCE,
        file
    }).then();
````

In return I am getting:

```
The request could not be understood by the server, please check your request is correctly formatted (status code 400) | {\\\"general\\\":\\\"Please ensure the Content-Type header is set correctly for a multi-part request\\\"}
```

I'll be really grateful if you could help me on that.

**Comment by ciaran16** [comment]
Hi @mkapiczy, I managed to upload base64 data at one point doing something like this:

```js
const buffer = Buffer.from(base64Data, 'base64');
const bufferStream = new PassThrough();
bufferStream.end(buffer);

const document = await onfido.document.upload({
  applicantId: 'applicant-123',
  file: {
    contents: bufferStream,
    filepath: 'path/to/file.jpg',
    contentType: 'image/jpeg'
  },
  type: type
});
```

Note that you'll need to know the content type of the base 64 data, and provide a filepath with a matching extension (it doesn't have to be a real filepath, `'image.jpg'` should do)

**Comment by mkapiczy** [comment]
That works, thanks! 

I would suggest to add it to the docs somewhere as a tip as it may be quite often scenario ;)
