### ISSUE TITLE
Docs and Typescript types out of date for Webhook 

### ISSUE THREAD

**Issue by bertrand-caron** [onfido/onfido-node#47]
As shown in the picture below: The Webhook object returns an `environments` keyword (right side of the image) which is not reflected in the documentation (left) and Typescript types. 

<img width="1428" alt="Screen Shot 2021-05-25 at 2 46 56 pm" src="https://user-images.githubusercontent.com/4724439/119440731-377b2d80-bd68-11eb-959c-8af3a670ba1f.png">

[Relevant documentation section](https://documentation.onfido.com/#webhook-object)

**Comment by Phoebe-B** [comment]
Hi @bertrand-caron. Thank you for raising. Please see [this PR](https://github.com/onfido/onfido-node/pull/48) which implements these changes. If you have any comments, please let us know. We will also update our documentation to reflect this change.

**Comment by Phoebe-B** [comment]
The PR has been merged in a patch release. We will close this issue if we don't hear from you in the next few days but feel free to open a new issue if you have any further issues. Thanks.

**Comment by bertrand-caron** [comment]
Thanks @Phoebe-B , Typescript changes look good; feel free to close as soon as you've upgraded the docs :)
