### ISSUE TITLE
'the Onfido SDKs' link in the readme is broken

### ISSUE THREAD

**Issue by barna-ratki-moonfare** [onfido/onfido-node#61]
Hello,

As the title says, the 'the Onfido SDKs' link in your readme leads to a 404 page. The contents of that page might have possibly been moved since the writing of said README.md.

Cheers,

**Comment by Phoebe-B** [comment]
Hi @barna-ratki-moonfare, thank you for highlighting this issue. I have opened [a PR here](https://github.com/onfido/onfido-node/pull/62) to address it and fix the links to point to our available SDKs.

**Comment by Phoebe-B** [comment]
I have now merged the fix so the links should no longer 404. Please do get in touch if there is anything else we can help with! 😃

**Comment by barna-ratki-moonfare** [comment]
Thanks for the fix :)
