### ISSUE TITLE
Build time issue

### ISSUE THREAD

**Issue by gvinsot** [onfido/onfido-node#81]
Hello,

Since last version this package needs more than 25 minutes to build (before it was negligeable)
This slows down hugely our build time and CICD.

Using "@onfido/api": "^2.3.1"

Any idea ?

Best regards

**Comment by sergiomartins8** [comment]
Hello @gvinsot!

Can you let us know what was the previous version you had going on?

**Comment by gvinsot** [comment]
I'm sorry but I don't have this information anymore... however 25 min build time seems excessive

**Comment by dvacca** [comment]
Hello @gvinsot,
Do you have any evidence that the delay was caused by @onfido/api? Can you exclude any temporary networking issue on your side, or any other issue with npm/yarn? Furthermore, do you have any output or log to share with us? Thanks.

**Comment by gvinsot** [comment]
Sorry, did a mistake the issue seems on the ui sdk side, reopening it with more logs on ui side

**Comment by gvinsot** [comment]
Sorry, did a mistake the issue seems on the ui sdk side, reopening it with more logs on ui side
